name: Python CRUD CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: crud_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install flask flask-mysqldb pytest
     # - name: Setup tmate session
     #   uses: mxschmitt/action-tmate@v3
      - name: Run script
        run: python app.py & sleep 10
        
      - name: Run tests
        run: pytest
        
      - name: Save API Response to file
        run: curl http://127.0.0:50000 > response1.json

      - name: Upload Response
        uses: actions/upload-artifact@v4
        with:
          name: api-output
          path: response1.json
